[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
location_registry = "8oer2N17ZmMGyE3xJepNjqi2hn1EU4CwUeSWwB38PPdZ"
witness = "27J4UkeFkTWmkz7dBv3JLM72pPN3DxRocDTigNhBgKqH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --detectOpenHandles --forceExit --watch"
